apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: microservices
build:
  artifacts:
  - image: mrzeal025/client
    context: client
    docker:
      dockerfile: Dockerfile
  - image: mrzeal025/comments
    context: comment
    docker:
      dockerfile: Dockerfile
  - image: mrzeal025/event-bus
    context: event-bus
    docker:
      dockerfile: Dockerfile
  - image: mrzeal025/moderation
    context: moderation
    docker:
      dockerfile: Dockerfile
  - image: mrzeal025/posts
    context: post
    docker:
      dockerfile: Dockerfile
  - image: mrzeal025/query
    context: query
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - infra/k8s/client-depl.yaml
    - infra/k8s/comments-depl.yaml
    - infra/k8s/event-bus-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/moderation-depl.yaml
    - infra/k8s/posts-depl.yaml
    - infra/k8s/query-depl.yaml
